http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  # test:
  #   host: localhost
  #   paths: '/test'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  # fastapi:
  #   url: 'http://localhost:8000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  
  # gateway1:
  #   apiEndpoints:
  #     - test
  #   policies:
  #   # Uncomment `key-auth:` when instructed to in the Getting Started guide.
  #     - key-auth:
  #     #- basic-auth:
  #     - proxy:
  #         - action:
  #             serviceEndpoint: fastapi 
  #             changeOrigin: true


